### PR TITLE
missed hypen at line #4

### PR DESCRIPTION
**Pull request by ObuhovR**
Caused errror like "These dependencies were not found: * notosans-fontface/fonts/NotoSansBold.eot"

### CODE REVIEW

**Comment by KostyaEsmukov** [comment]
The last version is broken because of that. An older version `1.1.0` works fine.

**Comment by b1f6c1c4** [comment]
@GreatWizard Could you have a look at this bug. `notosans-fontface` newest version (v1.2.1) contains a bug that makes the package unusable by emitting such error:
```
Error: ENOENT: no such file or directory, open '.../node_modules/notosans-fontface/fonts/NotoSansBoldItalic.eot'
```
Related to #5

**Review by GreatWizard — APPROVED** [review]

**Comment by GreatWizard** [comment]
I'm sorry to forgot this PR.
I will do the release today with the fix.

**Comment by GreatWizard** [comment]
Clsoe in favor of https://github.com/GreatWizard/notosans-fontface/pull/9

**Comment by GreatWizard** [comment]
v1.2.2 is released with the fix

**Pull request closed without merging**
